### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by Trictonicmp** [Trictonicmp/space-traveler#65]
#### There's two people in the team:
@Amedzro-Elikplim 
@Trictonicmp 

Project link:
https://github.com/Trictonicmp/space-traveler/projects/2

**Comment by Amedzro-Elikplim** [comment]
Hi @Kingstalux. Thanks for the review. Can you elaborate on the point you made

**Comment by Kingstalux** [comment]
> Hi @Kingstalux. Thanks for the review. Can you elaborate on the point you made

Submit the link to your Github project where your kanban board is found and not your repo link.

**Comment by BenMukebo** [comment]
### Hi @

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- Link to your GitHub project is present 👍🏻 
- You've provided information about the number of people in your group 👍🏻 

 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] Great job implementing the board by the copy of this template board: [https://github.com/microverseinc/curriculum-react-redux/projects/1](https://github.com/microverseinc/curriculum-react-redux/projects/1). However * For a team with **two** people the **Number of cards in Backlog should be equal to 17.** I can see that you only have 16 cards on your board, kindly add the missing cards and make sure you have only 17 cards on your kanban board 💯 😄 

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by medaminedev66** [comment]
Hi @Trictonicmp and @Amedzro-Elikplim, 

Your project is complete! Wishing you the best of success with your capstone project. 😃  
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Trictonicmp** [comment]
Thank you so much @medaminedev66!!
